apiVersion: v1
kind: Service
metadata:
  labels:
    app: mail-server
  name: mail-server
  namespace: lule
spec:
  ports:
  - name: imap
    nodePort: 30070
    port: 143
    protocol: TCP
    targetPort: 143
  - name: smtp
    nodePort: 30071
    port: 25
    protocol: TCP
    targetPort: 25
  - name: smtp-ssl
    nodePort: 30072
    port: 587
    protocol: TCP
    targetPort: 587
  - name: imap-ssl
    nodePort: 30073
    port: 993
    protocol: TCP
    targetPort: 993
  - name: pop
    nodePort: 30074
    port: 110
    protocol: TCP
    targetPort: 110
  - name: pop-ssl
    nodePort: 30075
    port: 995
    protocol: TCP
    targetPort: 995
  selector:
    app: mail-server
  type: NodePort

